<?php
/* @var $this HistoriaclinicaController */
/* @var $model Historiaclinica */

$this->breadcrumbs=array(
	'Historias Clinicas'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'Lista de  Historias Clinica', 'url'=>array('index')),
	array('label'=>'Crear Historia Clinica', 'url'=>array('create')),
	array('label'=>'Actualizar Historia Clinica', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Eliminar Historia Clinica', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Administrar Historias Clinicas', 'url'=>array('admin')),
);
?>

<h1>Ver Historia Clinica #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'fechaHistoria',
		'cedula',
		'apellidoPaterno',
		'apellidoMaterno',
		'primerNombre',
		'segundoNombre',
		'direccion',
		'barrio',
		'canton',
		'provincia',
		'telefono',
		'fechaNacimiento',
		'lugarNacimiento',
		'nacionalidad',
		'grupoCultural',
		'edad',
		'sexo',
		'estadoCivil',
		'instruccionAprobada',
		'ocupacion',
		'historiaLaboralPasada',
		'convulsiones',
		'tosConFlemaConSangre',
		'fracturas',
		'cirugia',
		'alergia',
		'ira',
		'hospitalizacion',
		'otros',
		'hta',
		'cardiopatia',
		'hipotiroidismo',
		'Diabetes',
		'cancer',
		'epilepsia',
		'enfermedadPulmonar',
		'detalleAntecedentesPatologicos',
		'menarquia',
		'cm',
		'disminorrea',
		'fum',
		'planificacionFamiliar',
		'papanicolao',
		'ecoMamario',
		'mamografia',
		'gesta',
		'menopausia',
		'aborto',
		'ivs',
		'partos',
		'cesareas',
		'hv',
		'hm',
		'detalleginecoObstetriz',
		'fuma',
		'drogas',
		'alcohol',
		'parejasSexuales',
		'medicamentosHabituales',
		'detalleHabitosToxicos',
		'peso',
		'talla',
		'imc',
		'valnut',
		'ta',
		'fc',
		'fr',
		'sat',
		'detalleEnfermedadActual',
		'detalleExamenFisico',
		'diagnosticoClinico',
		'tratamiento',
	),
)); ?>
